services:
  # Backend Service
  - type: web
    name: apex-car-rental-backend
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d7st1rbbc2fs73d3ighg-a:5432/car_rental_qnd8
      - key: SPRING_DATASOURCE_USERNAME
        value: apex_user
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false

databases:
  - name: apex-car-rental-db
    databaseName: car_rental
    user: apex_user
    plan: free
